# CI de Nível 03 - Disparo automático sempre que a pipeline de deploy for concluída. 

name: 'CI Nível 03 - Execução por Deploy'

on:
    workflow_run:
      workflows: ['CI Nível 01 - Execução Manual']
      types:
        - completed
      

jobs:
    e2e-tests:
        runs-on: ['ubuntu-latest']
        
        steps:

            - uses: actions/checkout@v4

            - name: Instalando Yarn
              run: npm install -g yarn

            - name: Instalando Dependências
              run: yarn
            
            - name: Instalando Playwright
              run: yarn playwright install

            - name: Execução de Testes E2E (end-to-end)
              run: yarn run e2e

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: relatorio-de-testes
                path: ./playwright-report
